title: Yicheng Kang
logo: /assets/headshot.heic
description: Hello! I am an aspiring technologist and lifelong learner, fervent on leveraging ML-driven solutions to improve quality of life and foster a sustainable future. Currently pursuing a Master of Science in Electrical and Computer Engineering at the University of California, Irvine, with an emphasis in Machine Learning and Data Science.
#show_downloads: true
theme: jekyll-theme-minimal
