title: Yicheng Kang
#logo: /assets/headshot.heic
description: Hello and welcome to my portfolio! I am an aspiring technologist and lifelong learner, fervent on leveraging ML-driven solutions to improve quality of life and foster a sustainable future. Currently pursuing a Master of Science in Electrical and Computer Engineering at the University of California, Irvine, with an emphasis in Machine Learning and Data Science. Thanks for stopping by!    p.s. scroll to the bottom to check out my current favorites!
#show_downloads: true
theme: jekyll-theme-minimal
